baseurl = "http://www.rushiagr.com"
languageCode = "en-us"
title = "rushiagr"
theme = "hyde"
copyright = "Rushi Agrawal"

[Author]
	name = "Rushi Agrawal"

[Permalinks]
	blog = "blog/:year/:month/:day/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "yet another tech guy"
	twitter = "https://twitter.com/rushiagr"
	github = "https://github.com/rushiagr"
	disqus = "rushiagr"
    linkedin = "https://www.linkedin.com/in/rushi-agrawal-0b799b15"
