baseurl = "http://www.rushiagr.com"
languageCode = "en-us"
title = "rushiagr"
theme = "hyde"
copyright = "Rushi Agrawal"

[Author]
	name = "Rushi Agrawal"

[Permalinks]
	blog = "blog/:year/:month/:day/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Rushi Agrawal"
	twitter = "https://twitter.com/rushiagr"
	github = "https://github.com/rushiagr"
	disqus = "rushiagr"
